services:
  searxng:
    image: docker.io/searxng/searxng:latest
    volumes:
      - ./searxng:/etc/searxng:rw
    ports:
      - 31336:8080

  perplexica-backend:
    build:
      context: .
      dockerfile: backend.dockerfile
      args:
        - SEARXNG_API_URL=http://127.0.0.1:31336
    depends_on:
      - searxng
    network_mode: host

  perplexica-frontend:
    build:
      context: .
      dockerfile: app.dockerfile
      args:
        - NEXT_PUBLIC_API_URL=http://127.0.0.1:31338/api
        - NEXT_PUBLIC_WS_URL=ws://127.0.0.1:31338
        - PORT=31337
    depends_on:
      - perplexica-backend
    ports:
      - 31337:31337
