services:
  searxng:
    image: docker.io/searxng/searxng:latest
    volumes:
      - ./searxng:/etc/searxng:rw
    ports:
      - 31336:8080
    networks:
      - perplexica-network

  perplexica-backend:
    build:
      context: .
      dockerfile: backend.dockerfile
      args:
        - SEARXNG_API_URL=http://searxng:8080
    depends_on:
      - searxng
    ports:
      - 31338:31338
    networks:
      - perplexica-network

  perplexica-frontend:
    build:
      context: .
      dockerfile: app.dockerfile
      args:
        - NEXT_PUBLIC_API_URL=http://127.0.0.1:31338/api
        - NEXT_PUBLIC_WS_URL=ws://127.0.0.1:31338
        - PORT=31337
    depends_on:
      - perplexica-backend
    ports:
      - 31337:31337
    networks:
      - perplexica-network

networks:
  perplexica-network: