[GENERAL]
PORT = 3001 # Port to run the server on
SIMILARITY_MEASURE = "cosine" # "cosine" or "dot"

[API_KEYS]
OPENAI = "sk-1234567890abcdef1234567890abcdef" # OpenAI API key

[API_ENDPOINTS]
SEARXNG = "http://localhost:32768" # SearxNG API ULR